add_newline = false
format = "$hostname$directory$git_branch$git_state$git_status$cmd_duration$line_break$character"

[character]
success_symbol = "❯"
error_symbol = "❯"
vimcmd_symbol = "❮"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"

[git_branch]
symbol = " "
style = "purple"

[cmd_duration]
min_time = 200
show_milliseconds = true
